### ISSUE TITLE
No explosions?

### ISSUE THREAD

**Issue by andalusiandonkey** [apace100/origins-forge#1]
Hello ! im having trouble creating datapacks for this mod , i have succesfully created a few but i have just realized now that no matter how hard i try i cant make things explode through datapacks, for example i can make myself explode , it will deal dmg but it doesnt break or destroy blocks at all , i have checked and re-checked the code and its correct , i tried different working datapacks and they also fail at destroying/breaking blocks.

On a side note , is there a wiki or a place where i can learn/make questions about the creation of datapacks for this mod ? all i have is the fabric discord and wiki and understandably enough they cant answer my questions. 

thank you kindly.

**Comment by apace100** [comment]
Hello!
I assume you're talking about [this mod](https://www.curseforge.com/minecraft/mc-mods/origins-forge)?
In that case - this is not the repository for that. That mod's code is hosted at https://github.com/EdwinMindcraft/origins-architectury.

However, please don't create issues for datapack questions. The issue board is there for _bug reports_, not _support questions_.

That being said, the [wiki for the Fabric version of the mod](https://origins.readthedocs.io/en/latest/) should answer your questions regarding datapacks, as the Forge version maintains feature parity and datapacks between the Fabric and Forge version are (in most cases) interchangable.
In particular, you'd want to be using the [explode entity action](https://origins.readthedocs.io/en/latest/types/entity_action_types/explode/) to create an explosion.

Feel free to visit the [Origins Discord](https://discord.gg/VdGgwXwWNa) if you need further assistance.
