### ISSUE TITLE
Selection Menu not Displaying on World Join

### ISSUE THREAD

**Issue by otectus** [apace100/origins-forge#5]
So no matter what I seem to try, I can't get the selection menu for Origins to show up when I start a new world. I can if I use the orb but I'd really like to get it to where the menu will show up on its own without the need for that. Weirder is that until I select an origin via orb, I am invulnerable to any and all damage. I am running the Origins Forge mod alongside TooManyOrigins, Origins Accessibilities and Origins Classes but I have the same issue even running "Origins" alone. It's worth noting that the modpack also contains several hundred other mods but I can't seem to pinpoint which, if any, are causing the issue.

Any help would be so greatly appreciated! It's driving me a bit mad. ^^" I assume that perhaps another mod in the modpack is conflicting with it resulting in the menu not showing on world join but I don't know which it could possibly be. I am happy to provide any additional information which might prove useful in deducing the culprit.

**Comment by otectus** [comment]
Update: If I leave the world and rejoin it, the menu does come up on joining. Not sure if that might be of any help!

**Comment by otectus** [comment]
Never mind, it appears to have been a conflict with the FactionCraft and/or Reputation mods. I disabled them and it is now functioning properly. Closing.

**Comment by kotazzz** [comment]
Still a problem. The player was immortal until he chose origin. At the first login he didn't see the menu at all, but he could hit everyone and I couldn't. The zombie was unable to do damage to the player
